language: go

env:
  - GO111MODULE=on

install: 
  - go get ./...

script:
  - go fmt ./...
  - go vet ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)